version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    assignees:
      - "dinmukhamednurkaliyev"
    reviewers:
      - "dinmukhamednurkaliyev"
    labels:
      - "type/chore"
      - "area/ci"
      - "dependencies"
    groups:
      actions-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      actions-major:
        patterns:
          - "*"
        update-types:
          - "major"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    rebase-strategy: "auto"

  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    assignees:
      - "dinmukhamednurkaliyev"
    reviewers:
      - "dinmukhamednurkaliyev"
    labels:
      - "type/chore"
      - "area/flutter"
      - "dependencies"
    groups:
      flutter-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      flutter-major:
        patterns:
          - "*"
        update-types:
          - "major"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    rebase-strategy: "auto"

  - package-ecosystem: "gradle"
    directory: "/android"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    assignees:
      - "dinmukhamednurkaliyev"
    reviewers:
      - "dinmukhamednurkaliyev"
    labels:
      - "type/chore"
      - "area/android"
      - "dependencies"
    groups:
      android-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      android-major:
        patterns:
          - "*"
        update-types:
          - "major"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    rebase-strategy: "auto"
