name: "Bot: Triage & Labeler"

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  triage:
    name: "Triage PR"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v6.0.1
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          sparse-checkout: .github/labeler.yaml

      - name: "Run Labeler"
        uses: actions/labeler@v6.0.1
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          sync-labels: true
          configuration-path: .github/labeler.yaml
