name: "Release Build"

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run:
    name: "Build"
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: "Git: Checkout"
        uses: actions/checkout@v6.0.1

      - name: "Flutter: Setup"
        uses: ./.github/actions/setup-flutter/
        id: setup

      - name: "Flutter: Build APK"
        if: steps.setup.outputs.installed == 'true'
        id: build
        uses: ./.github/actions/build-android/
        with:
          flavor: "development"
          mode: "debug"
          target: "lib/main_development.dart"
          version-tag: ${{ github.event.release.tag_name || 'manual' }}

      - name: "GitHub: Upload Assets"
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v2.5.0
        with:
          files: fitness-tracker-development-*.apk
