name: "Check: Analyze"

on:
  workflow_call:

permissions:
  contents: read

jobs:
  analyze:
    name: "Analyze Code"
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v6.0.1

      - name: "Flutter: Setup"
        uses: ./.github/actions/setup-flutter/
        id: setup

      - name: "Flutter: Analyze"
        if: steps.setup.outputs.installed == 'true'
        run: melos run analyze:all
