name: "Check: Lint"

on:
  workflow_call:

permissions:
  contents: read

jobs:
  lint:
    name: "Lint Code"
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v6.0.1

      - name: "Flutter: Setup"
        uses: ./.github/actions/setup-flutter/
        id: setup

      - name: "Flutter: Check Formatting"
        if: steps.setup.outputs.installed == 'true'
        run: melos run format:check
