name: "Continuous Integration: Lint"

on:
  workflow_call:

permissions:
  contents: read

jobs:
  run:
    name: "Run"
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: "Git: Checkout"
        uses: actions/checkout@v6.0.1

      - name: "Flutter: Setup"
        uses: ./.github/actions/flutter_setup/
        id: setup

      - name: "Melos: Lint"
        if: steps.setup.outputs.installed == 'true'
        run: melos run format:check
