name: "Continuous Integration: Spell Check"

on:
  workflow_call:

permissions:
  contents: read
  pull-requests: write

jobs:
  spellcheck:
    name: "Spell Check with cspell"
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: "Git: Checkout"
        uses: actions/checkout@v6.0.1
        with:
          fetch-depth: 0

      - name: "Spell Check"
        uses: streetsidesoftware/cspell-action@v8
        with:
          config: ./cspell.json
          inline: warning
          incremental_files_only: true
          strict: true
          check_dot_files: explicit
